Data Kuantitatif terhadap kolom data Usia

In [1]:
import pandas as pd
from IPython.display import display

# Baca file Excel
df = pd.read_excel('Dataset_Tubes.xlsx')

# Ambil kolom usia
usia = df['Usia__dalam_tahun'].dropna()

# Hitung statistik deskriptif
mean = usia.mean()
q1 = usia.quantile(0.25)
median = usia.median()
q3 = usia.quantile(0.75)
p5 = usia.quantile(0.05)
p95 = usia.quantile(0.95)
std_dev = usia.std()
variance = usia.var()
minimum = usia.min()
maximum = usia.max()

# Buat DataFrame hasil statistik
stat_df = pd.DataFrame({
    "Statistik": [
        "Mean",
        "Q1 (25th percentile)",
        "Median (Q2)",
        "Q3 (75th percentile)",
        "P5 (5th percentile)",
        "P95 (95th percentile)",
        "Standard Deviation",
        "Variance",
        "Minimum",
        "Maximum"
    ],
    "Nilai": [
        f"{mean:.2f}",
        f"{q1:.2f}",
        f"{median:.2f}",
        f"{q3:.2f}",
        f"{p5:.2f}",
        f"{p95:.2f}",
        f"{std_dev:.2f}",
        f"{variance:.2f}",
        f"{minimum:.2f}",
        f"{maximum:.2f}"
    ]
})

print("=== Statistik Deskriptif: Usia (dalam tahun) ===")
display(stat_df)

=== Statistik Deskriptif: Usia (dalam tahun) ===

               Statistik   Nilai
0                   Mean   27.44
1   Q1 (25th percentile)   19.00
2            Median (Q2)   21.00
3   Q3 (75th percentile)   33.25
4    P5 (5th percentile)   18.00
5  P95 (95th percentile)   54.00
6     Standard Deviation   12.29
7               Variance  150.95
8                Minimum   10.00
9                Maximum   77.00

Data kuantitatif untuk Modus dan Tabel Frekuensi pada Jenis Kelamin

In [4]:
import pandas as pd
from IPython.display import display

# Baca file excel
df = pd.read_excel('Dataset_Tubes.xlsx')

# Ambil kolom jenis kelamin
jenis_kelamin = df['Jenis_kelamin'].dropna()

# Hitung banyak sampel (untuk perhitungan proporsi)
jumlah_sampel = len(jenis_kelamin)

# Perhitungan frekuensi dan proporsi
frekuensi = jenis_kelamin.value_counts()
proporsi = (frekuensi / jumlah_sampel * 100).round(4)

# Tabel Frekuensi & Proporsi
tabel = pd.DataFrame({
    'Frekuensi': frekuensi,
    'Proporsi (%)': proporsi
})

# Menghitung modus (kategori dengan frekuensi tertinggi)
modus = tabel['Frekuensi'].idxmax()

print("=== Tabel Frekuensi & Proporsi Jenis Kelamin ===")
display(tabel)
print(f"Modus: {modus}")

=== Tabel Frekuensi & Proporsi Jenis Kelamin ===

               Frekuensi  Proporsi (%)
Jenis_kelamin
Perempuan            544          54.4
Laki-laki            456          45.6

Modus: Perempuan

Data kuantitatif untuk Modus dan Tabel Frekuensi pada Penghasilan per Bulan

In [6]:
import pandas as pd
from IPython.display import display

# Baca file excel
df = pd.read_excel('Dataset_Tubes.xlsx')

# Ambil kolom penghasilan per bulan
penghasilan = df['Penghasilan_per_bulan'].dropna()

# Hitung banyak sampel (untuk perhitungan proporsi)
jumlah_sampel_penghasilan = len(penghasilan)

# Perhitungan frekuensi dan proporsi
frekuensi = penghasilan.value_counts()
proporsi = (frekuensi / jumlah_sampel_penghasilan * 100).round(4)

# Tabel Frekuensi & Proporsi
tabel = pd.DataFrame({
    'Frekuensi': frekuensi,
    'Proporsi (%)': proporsi
})

# Menghitung modus (kategori dengan frekuensi tertinggi)
modus = tabel['Frekuensi'].idxmax()

print("=== Tabel Frekuensi & Proporsi Penghasilan Setiap Bulan ===")
display(tabel)
print(f"Modus: {modus}")

=== Tabel Frekuensi & Proporsi Penghasilan Setiap Bulan ===

                         Frekuensi  Proporsi (%)
Penghasilan_per_bulan
< Rp 2 juta                    469          46.9
Rp 2 juta – Rp 5 juta          237          23.7
Rp 5 juta – Rp 10 juta         131          13.1
Rp 10 juta - Rp 20 juta        102          10.2
> Rp 20 juta                    61           6.1

Modus: < Rp 2 juta

In [7]:
import pandas as pd
from IPython.display import display

# Baca file excel
df = pd.read_excel('Dataset_Tubes.xlsx')

# Ambil kolom intensitas aktivitas online
intensitas_online = df['Menurut_Anda__bagaimana_intensitas_aktivitas_online_Anda_dalam_3_bulan_terakhir'].dropna()

# Hitung banyak sampel (untuk perhitungan proporsi)
jumlah_sampel_intensitas_online = len(intensitas_online)

# Perhitungan frekuensi dan proporsi
frekuensi = intensitas_online.value_counts()
proporsi = (frekuensi / jumlah_sampel_intensitas_online * 100).round(4)

# Tabel Frekuensi & Proporsi
tabel = pd.DataFrame({
    'Frekuensi': frekuensi,
    'Proporsi (%)': proporsi
})

# Menghitung modus (kategori dengan frekuensi tertinggi)
modus = tabel['Frekuensi'].idxmax()

print("=== Tabel Frekuensi & Proporsi Intensitas Aktivitas Online ===")
display(tabel)
print(f"Modus: {modus}")

=== Tabel Frekuensi & Proporsi Intensitas Aktivitas Online ===

                                                    Frekuensi  Proporsi (%)
Menurut_Anda__bagaimana_intensitas_aktivitas_on...
Tinggi                                                    399          39.9
Sangat tinggi                                             363          36.3
Sedang                                                    206          20.6
Rendah                                                     26           2.6
Sangat rendah                                               6           0.6

Modus: Tinggi

In [8]:
import pandas as pd
from IPython.display import display

# Baca file excel
df = pd.read_excel('Dataset_Tubes.xlsx')

# Ambil kolom intensitas pakai AI
intensitas_pakai_AI = df['Apakah_Anda_Pernah_menggunakan_aplikasi__layanan_AI__Seberapa_sering_Anda_menggunakan_aplikasi__layanan_AI'].dropna()

# Hitung banyak sampel (untuk perhitungan proporsi)
jumlah_sampel_intensitas_pakai_AI = len(intensitas_pakai_AI)

# Perhitungan frekuensi dan proporsi
frekuensi = intensitas_pakai_AI.value_counts()
proporsi = (frekuensi / jumlah_sampel_intensitas_pakai_AI * 100).round(4)

# Tabel Frekuensi & Proporsi
tabel = pd.DataFrame({
    'Frekuensi': frekuensi,
    'Proporsi (%)': proporsi
})

# Menghitung modus (kategori dengan frekuensi tertinggi)
modus = tabel['Frekuensi'].idxmax()

print("=== Tabel Frekuensi & Proporsi Intensitas Pakai AI Setiap Bulan ===")
display(tabel)
print(f"Modus: {modus}")

=== Tabel Frekuensi & Proporsi Intensitas Pakai AI Setiap Bulan ===

                                                    Frekuensi  Proporsi (%)
Apakah_Anda_Pernah_menggunakan_aplikasi__layana...
Ya, sering (hampir setiap hari)                           324          32.4
Ya, kadang-kadang (beberapa kali seminggu)                258          25.8
Ya, sangat sering (setiap hari)                           204          20.4
Pernah, tapi sangat jarang                                 76           7.6
Tidak pernah                                               71           7.1
Ya, jarang (beberapa kali sebulan)                         67           6.7

Modus: Ya, sering (hampir setiap hari)

In [9]:
import pandas as pd
from IPython.display import display

# Baca file excel
df = pd.read_excel('Dataset_Tubes.xlsx')

# Ambil kolom waktu pakai AI
waktu_pakai_AI = df['Dalam_aktivitas_sehari_hari__berapa_banyak_waktu_yang_Anda_habiskan_menggunakan_layanan_berbasis_AI'].dropna()

# Hitung banyak sampel (untuk perhitungan proporsi)
jumlah_sampel_waktu_pakai_AI = len(waktu_pakai_AI)

# Perhitungan frekuensi dan proporsi
frekuensi = waktu_pakai_AI.value_counts()
proporsi = (frekuensi / jumlah_sampel_waktu_pakai_AI * 100).round(4)

# Tabel Frekuensi & Proporsi
tabel = pd.DataFrame({
    'Frekuensi': frekuensi,
    'Proporsi (%)': proporsi
})

# Menghitung modus (kategori dengan frekuensi tertinggi)
modus = tabel['Frekuensi'].idxmax()

print("=== Tabel Frekuensi & Proporsi Waktu Pakai AI Setiap Hari ===")
display(tabel)
print(f"Modus: {modus}")

=== Tabel Frekuensi & Proporsi Waktu Pakai AI Setiap Hari ===

                                                    Frekuensi  Proporsi (%)
Dalam_aktivitas_sehari_hari__berapa_banyak_wakt...
Kurang dari 1 jam                                         489          48.9
1–2 jam                                                   303          30.3
2–4 jam                                                   145          14.5
Lebih dari 4 jam                                           63           6.3

Modus: Kurang dari 1 jam